### ISSUE TITLE
Issues with setting up external adsb receiver

### ISSUE THREAD

**Issue by JayBraker** [mikenye/docker-piaware#134]
Hi, I have dump1090 (not dump1090fa) running on the host, exposing its interface to 0.0.0.0:30002
Installed this container with
```
extra_hosts:
  - "host.docker.internal:host-gateway"
 environment:
  - BEASTHOST=host.docker.internal
  - BEASTPORT=30002
  - RECEIVER_TYPE=relay
```
Which makes the feed available on host host.docker.internal:30002
However piaware does not ingest, writing "framing errors seen, is the peer sending Beast binary data?" to the log.
I assume faupload1090 (gets mentioned in the logs, unfortunately not at all documented) would need to be reconfigured to connect to my receiver.

Does anyone have experience with this kind of issue?
Feeds for fr24 and adsbx run flawlessly

**Comment by mikenye** [comment]
Try port `30005`.
