### ISSUE TITLE
Health check script doesn't support IPv6

### ISSUE THREAD

**Issue by bootc** [mikenye/docker-piaware#135]
I've been running this container in my Kubernetes cluster which has dual-stack networking, and the PiAware daemon happily connects to FlightAware using IPv6. Unfortunately the health check script's regexes exclude IPv6 addresses so the health check always fails.

In addition, `netstat` and other tools from the net-tools suite are deprecated; it would be better to switch to `ss` to get the same information.

I'll prepare a PR which fixes this.

**Comment by mikenye** [comment]
Thanks so much, sorry it took so long to review & merge.
