### ISSUE TITLE
After Upgrading "couldn't open socket: cannot assign requested address"

### ISSUE THREAD

**Issue by PaulGoldschmidt** [mikenye/docker-piaware#140]
Hey y'all,

after upgrading docker-piaware to the latest version, the container couldn't receive any flight information, after executing piaware-status I figured out that the socket could not be opend by piaware - any idea why that is the case? I manually downgraded to 7.1 and the problem disappeared.

All the best,
Paul

**Comment by kx1t** [comment]
Could you post some of the container logs?
Maybe do something like `docker restart piaware && sleep 20 && docker logs piaware` and post the results here? 
(There is 1 line in the logs that you should definitely obfuscate before posting:
`Set feeder-id to 7xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxb in /etc/piaware.conf:1`
