### ISSUE TITLE
Health Check for 978 fails

### ISSUE THREAD

**Issue by challgren** [mikenye/docker-piaware#219]
The health check for dump978 fails. The log contains the following text

```
[2024-12-10 14:22:20.007][piaware] 2320 msgs recv'd from dump1090 (2010 in last 5m); 2320 msgs sent to FlightAware
[2024-12-10 14:22:20.008][piaware] 73 msgs recv'd from the ADS-B data program at dump978/30978 (66 in last 5m); 73 msgs sent to FlightAware
```

However when running `/scripts/healthcheck.sh` the output is

```
Connected to Flightaware, OK.
2320 dump1090 messages sent in past hour, OK.
0 dump978 messages sent in past 2 hours, NOT OK.
Webserver listening on port 80, OK.
Webserver listening on port 8080, OK.
```

It appears that `the ADS-B data program at` is messing up the regex in the healthcheck. Also the healthcheck.sh is hardcoded for `socat` instead of depending on the `UAT_RECEIVER_HOST` variable

**Comment by wiedehopf** [comment]
it was always socat until i changed it to remove the unnecessary socat.

but i don't run unnecessary healthchecks so i didn't notice.
(i'll fix it ... )
