### ISSUE TITLE
Suggestion: redirect directly to FlightAware user statistics page

### ISSUE THREAD

**Issue by klara31** [mikenye/docker-piaware#24]
When clicking on the FlightAware logo on the top left, you are redirected to the FlightAware home page. It's a lot easier when you are directly redirected to your personal statistics page. When running locally, I was using the following patch:
```
--- /usr/share/dump1090-fa/html/index.html	2019-08-01 10:33:43.000000000 +0200
+++ /usr/share/dump1090-fa/html/index.html	2019-08-13 22:47:39.299981896 +0200
@@ -48,7 +48,7 @@
 
 		<div id="header" class="infoHeading">
 			<div class="logoContainer">
-				<a href="http://flightaware.com/" target="_blank"><img src="images/fa_logo_color.png" alt="FlightAware" class="flightawareLogo" srcset="images/fa_logo_color.png 1x, images/fa_logo_color@2x.png 2x, images/fa_logo_color@3x.png 3x"></a>
+				<a href="https://flightaware.com/adsb/stats/user/xxxxxxxxxxxxx" target="_blank"><img src="images/fa_logo_color.png" alt="FlightAware" class="flightawareLogo" srcset="images/fa_logo_color.png 1x, images/fa_logo_color@2x.png 2x, images/fa_logo_color@3x.png 3x"></a>
 				<img src="images/pa-sa-logo.png" alt="PiAware SkyAware" class="adsbLogo piAwareLogo" srcset="images/pa-sa-logo.png 1x, images/pa-sa-logo@2x.png 2x, images/pa-sa-logo@3x.png 3x">
 				<img src="images/ff-sa-logo.png" alt="FlightFeeder SkyAware" class="adsbLogo flightfeederLogo" srcset="images/ff-sa-logo.png 1x, images/ff-sa-logo@2x.png 2x, images/ff-sa-logo@3x.png 3x" style="display: none;">
 			</div>
```
Is it possible to implement this, probably using an runtime environment variable on this image?

Another request: add BING api key to the runtime environment variables.

**Comment by klara31** [comment]
Awesome! Thanks :)

**Comment by mikenye** [comment]
No worries! Did it work for you?

Also, I've been googling about using a Bing API key with `piaware`... Do you have any info on this or suggestions on how to implement?

**Comment by klara31** [comment]
config.js has a line for that:
```BingMapsAPIKey = "xxxxxxxxxxx";```
I already tried adding this line to config.js and that works OK.

**Comment by mikenye** [comment]
OK, the `latest` tag of the image should allow you to set `BINGMAPSAPIKEY`. Let me know how you fare.

**Comment by klara31** [comment]
Yep, working! Thanks again!

**Comment by mikenye** [comment]
You're most welcome!

**Comment by klara31** [comment]
The redirect to the user statistics page is gone...

**Comment by mikenye** [comment]
I'll check it out

**Comment by mikenye** [comment]
Ok this should now be fixed. Apologies for the inconvenience.

**Comment by klara31** [comment]
Confirmed! Thanks (-:
