### ISSUE TITLE
Start automatically

### ISSUE THREAD

**Issue by 0verzeal0us** [mikenye/docker-piaware#52]
I can use docker run to create and start the container and the device checks in. When I restart the device I have to manually restart it. Is there a way for it to start automatically?

**Comment by mikenye** [comment]
In your docker run command, include `--restart=always`, and the container will be restarted when the host reboots.

**Comment by 0verzeal0us** [comment]
Thank you!

**Comment by mikenye** [comment]
You're very welcome. :-)
