### ISSUE TITLE
PiAware v4.0

### ISSUE THREAD

**Issue by 0verzeal0us** [mikenye/docker-piaware#54]
Hi there, not really an issue but more of a request. Will you be updating this to support v4 of PiAware?

**Comment by mikenye** [comment]
Hi @0verzeal0us, sorry for the delayed reply - I somehow missed this...

The image has support for v4.0 - the `latest` tag of the image is v4.0 and there are specific tags for v4.0 (and earlier versions).

Kind regards,
Mike Nye

**Comment by 0verzeal0us** [comment]
Perfect! Thanks!
