### ISSUE TITLE
RTLSDR_PPM value not picked up

### ISSUE THREAD

**Issue by klara31** [mikenye/docker-piaware#55]
I have set the RTLSDR_PPM value in de docker.yml file. If I check the code, in etc/services.d/dump1090/run there is a line: RTLSDR_PPM="$(piaware-config -show rtlsdr-ppm)" 
But RTLSDR_PPM is not set to piaware-config. Hence the value is always 0.

Or am I missing something?

**Comment by mikenye** [comment]
You're correct. Oops. I'll fix this now. Sorry for the inconvenience.

**Comment by mikenye** [comment]
@klara31 I've implemented an attempted fix. Can you pull the `:latest` image and let me know if that solves your problem?

Thanks.

**Comment by klara31** [comment]
Yes, PPM value now is used correctly. Thanks again!

**Comment by mikenye** [comment]
You're most welcome. Thanks for reporting the issue.
