### ISSUE TITLE
Feature Request: Add PiAware Status Page

### ISSUE THREAD

**Issue by clarkchentw** [mikenye/docker-piaware#57]
- PiAware Status Page normally listen on port 80: https://github.com/flightaware/piaware-web

**Comment by mikenye** [comment]
Hi @clarkchentw, thanks for your suggestion. I've implemented it and the new image is currently building, it should be ready in 30 minutes or so.

Please let me know if you have any problems.

**Comment by mikenye** [comment]
Image is ready.
