### ISSUE TITLE
Healthcheck now failing on Docker

### ISSUE THREAD

**Issue by scottwallacesh** [mikenye/docker-piaware#60]
Missing healthcheck script:
```
# docker inspect piaware | jq .[].State.Health.Log[-1].Output 
"/bin/sh: 1: /healthcheck.sh: not found\n"
```

**Comment by mikenye** [comment]
Hi @scottwallacesh,

The current version of the container has the healthcheck commented out (while I work on it): <https://github.com/mikenye/docker-piaware/blob/dfa8dbda3f43f2338ea769599ececd862d94f994/Dockerfile#L281>

Are you manually specifying a healthcheck?

If so, I'd recommend disabling it for a few days while I re-write the healthcheck.

Sorry for the inconvenience.

-Mike

**Comment by mikenye** [comment]
FYI - I'd recently made a significant amount of changes in order to properly implement UAT (dump978/skyaware978), which broke the healthcheck. Rather than delay the release of the image by rewriting the healthcheck code, I figured I'd release the new version with the healthcheck disabled, and finish the healthcheck over the next day or two.

**Comment by scottwallacesh** [comment]
> Are you manually specifying a healthcheck?

No.  I'm simply using `mikenye/piaware` from Docker Hub:
```
# docker image pull mikenye/piaware:latest 
latest: Pulling from mikenye/piaware
Digest: sha256:dc21f1cf2aab5758b5940a9d0eba20c8b75fd1483891f0cfa475972f2329054b
Status: Image is up to date for mikenye/piaware:latest
docker.io/mikenye/piaware:latest
```

**Comment by mikenye** [comment]
Can you run `uname -m` on the host with the problem and post the output so I know which architecture to test on?

**Comment by scottwallacesh** [comment]
Ahh... it appears that `docker-compose` hangs on the the concept of a healthcheck until the container is removed and recreated.  Simply recreating with a new image wasn't enough as it still said that a healthcheck existed.

Sorted now.

**Comment by scottwallacesh** [comment]
> Can you run `uname -m` on the host with the problem and post the output so I know which architecture to test on?

```
# uname -m
x86_64
```

**Comment by mikenye** [comment]
Oh that's really annoying. I didn't realise.

I'll try and get the healthcheck finished ASAP.
