### ISSUE TITLE
healthcheck checks for wrong piaware servers and returns exit code 1

### ISSUE THREAD

**Issue by jheinitz** [mikenye/docker-piaware#78]
Hello,

I'm quite happy with the docker image for PiAware. But I just found out that the healthcheck (/scripts/healthcheck.sh) tells me that my system is unhealthy. It tells me that there is no connection to Flightaware, but there is a valid connection. 

I think that the problem is that the valid IP addresses are taken from the command

`root@piaware:/# piaware-config -show adept-serverhosts`
`piaware.flightaware.com piaware.flightaware.com {70.42.6.156 70.42.6.232 70.42.6.224 70.42.6.228 70.42.6.198 70.42.6.225}`

When I issue a manual `netstat -an` I can see that there is a connection to 206.253.82.195 which resolves to gregs.dal.flightaware.com. 

So the question is: Where can I configure the list IPs? And why is my Piaware connectiing to this server?

Thanks in advance and best regards from Germany!

Jens

**Comment by mikenye** [comment]
This should now be fixed. I'll close this out.
