### ISSUE TITLE
piaware defaulting to wrong uat receiver port

### ISSUE THREAD

**Issue by wiedehopf** [mikenye/docker-piaware#86]
./rootfs/etc/services.d/978raw-splitter/run

```socat -d -d TCP-LISTEN:30978,fork TCP:"$UAT_RECEIVER_HOST":"${UAT_RECEIVER_PORT:-30979}" \```

change to
```socat -d -d TCP-LISTEN:30978,fork TCP:"$UAT_RECEIVER_HOST":"${UAT_RECEIVER_PORT:-30978}" \```

**Comment by mikenye** [comment]
Thanks. Fixed in 802b75b.
