### ISSUE TITLE
PiAware v6.0 adaptive gain

### ISSUE THREAD

**Issue by emilburzo** [mikenye/docker-piaware#87]
(The release announcement email barely came out and you already updated the docker images, amazing!)

One of the highlights of the v6 release seems to be the [adaptive gain](https://github.com/flightaware/dump1090/blob/master/README.adaptive-gain.md).

What would be the easiest way to try it out with the docker image?

**Comment by mikenye** [comment]
Hi @emilburzo, sorry for the delay in implementing this.

PR #124 implements the following:

> The following settings control the [adaptive gain configuration](https://github.com/flightaware/dump1090/blob/master/README.adaptive-gain.md) of `dump1090` when using `RECEIVER_TYPE=rtlsdr`.
> 
> | Environment Variable | Possible Values | Description | Default |
> | -------------------- | --------------- | ------- | ------- |
> | `DUMP1090_ADAPTIVE_RANGE` | `true` or unset | Set to any value to adjust gain for target dynamic range. | |
> | `DUMP1090_ADAPTIVE_RANGE_TARGET` | A value in dB | Set target dynamic range in dB. | |
> | `DUMP1090_ADAPTIVE_BURST` | `true` or unset | Set to any value to adjust gain for too-loud message bursts. | |
> | `DUMP1090_ADAPTIVE_MIN_GAIN` | A value in dB | Set gain adjustment range lower limit (dB). | |
> | `DUMP1090_ADAPTIVE_MAX_GAIN` | A value in dB | Set gain adjustment range upper limit (dB). | |
> | `DUMP1090_ADAPTIVE_DUTY_CYCLE` | A percentage | Set adaptive gain duty cycle % (1..100) </br> See [Reducing the CPU cost of adaptive gain](https://github.com/flightaware/dump1090/blob/master/README.adaptive-gain.md#reducing-the-cpu-cost-of-adaptive-gain) | |

**Comment by mikenye** [comment]
Once PR #124 is merged, this issue will automatically be closed. After this, the new image will build (will take about 1-2 hours). Once complete, please pull the image and update your container.

Please feel free to re-open the issue if you're still having problems after that.

Thanks.
